name: Android Instrumentation + UnitTests

on: [pull_request]

jobs:
  connected-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Check architecture
        run: uname -m

      - name: Set up JDK 17 (Required for sdkmanager)
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'temurin'
          cache: 'gradle'

      - name: Enable KVM
        run: |
          echo 'KERNEL=="kvm", GROUP="kvm", MODE="0666", OPTIONS+="static_node=kvm"' | sudo tee /etc/udev/rules.d/99-kvm4all.rules
          sudo udevadm control --reload-rules
          sudo udevadm trigger --name-match=kvm

      - name: Set up Gradle
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: 8.14.1
        env:
          GPR_USER: ${{ secrets.GPR_USER }}
          GPR_TOKEN: ${{ secrets.GPR_TOKEN }}

      - name: Run connected tests
        uses: ReactiveCircus/android-emulator-runner@v2
        with:
          api-level: 30
          target: google_apis
          arch: x86_64
          boot-timeout: 600
          script: |
            cd $GITHUB_WORKSPACE/Android/wallet
            ../gradlew connectedDebugAndroidTest --stacktrace
        env:
          GPR_USER: ${{ secrets.GPR_USER }}
          GPR_TOKEN: ${{ secrets.GPR_TOKEN }}

      - name: Upload test report
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: android-test-report
          path: Android/wallet/build/reports/androidTests/connected/debug/
