name: Android Instrumentation Tests

on: [push, pull_request]

jobs:
  instrumented-tests:
    runs-on: ubuntu-latest
    timeout-minutes: 20

    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 17
          cache: gradle

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3

      - name: Debug Directory Structure
        run: |
          echo "Listing files in repository root:"
          ls -la
          echo "Listing files in Android/:"
          ls -la Android
          echo "Listing files in Android/wallet/:"
          ls -la Android/wallet

      # Ensure Gradle wrapper exists
      - name: Generate Gradle Wrapper (if missing)
        run: |
         if [ ! -f "Android/gradlew" ]; then
           echo "gradlew not found! Generating it..."
           cd Android
           gradle wrapper
         fi
         
      - name: Grant execute permission for Gradle wrapper
        run: chmod +x Android/gradlew

      - name: Run Android Instrumented Tests
        uses: ReactiveCircus/android-emulator-runner@v2
        with:
          api-level: 30
          target: google_apis
          arch: x86_64
          profile: Nexus 6
          disable-animations: true
          emulator-options: > 
            -no-window -no-accel -gpu swiftshader_indirect -no-snapshot -noaudio -no-boot-anim 
            -camera-back none -camera-front none
          emulator-boot-timeout: 800
          script: |
            echo "Waiting for emulator to be online..."
            adb wait-for-device
            adb devices -l  # Debug: List devices
            adb logcat -d > adb_logcat.txt  # Capture logs for debugging
            adb shell "while [[ -z \$(getprop sys.boot_completed) ]]; do sleep 1; done"
            echo "Device is ready, restarting ADB..."
            adb kill-server
            adb start-server
            adb devices -l  # Check again after restart
            ./Android/gradlew :wallet:connectedDebugAndroidTest --stacktrace

      - name: Upload ADB Logs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: adb-logcat
          path: adb_logcat.txt
