name: Android Instrumentation Tests

on: [push, pull_request]

jobs:
  connected-tests:
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Check architecture
        run: uname -m

      - name: Set up JDK 17 (Required for sdkmanager)
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'temurin'
          cache: 'gradle'

      - name: Set up Android SDK
        run: |
          echo "ANDROID_HOME=$HOME/Library/Android/sdk" >> $GITHUB_ENV
          echo "ANDROID_SDK_ROOT=$HOME/Library/Android/sdk" >> $GITHUB_ENV
          echo "$ANDROID_HOME/cmdline-tools/latest/bin:$ANDROID_HOME/tools/bin:$ANDROID_HOME/platform-tools" >> $GITHUB_PATH

      - name: Install Emulator System Image
        run: |
          sdkmanager --install "system-images;android-30;google_apis;x86_64"
          yes | sdkmanager --licenses

      - name: Set environment variable to use system libs for emulator
        run: echo "ANDROID_EMULATOR_USE_SYSTEM_LIBS=1" >> $GITHUB_ENV

      - name: Run connected tests
        uses: ReactiveCircus/android-emulator-runner@v2
        with:
          api-level: 30
          target: google_apis
          arch: arm64-v8a
          system-image: "system-images;android-30;google_apis;arm64-v8a"
          emulator-options: -accel off
          disable-hypervisor: true
          script: |
            cd Android/wrapper
            adb wait-for-device
            adb devices -l
            adb shell "while [[ -z $(getprop sys.boot_completed) ]]; do sleep 1; done"
            ./gradlew connectedDebugAndroidTest --stacktrace
