name: Android Tests

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Generate Gradle Wrapper
        run: gradle wrapper
        working-directory: Android

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
        working-directory: Android

      - name: Run Android Tests
        run: ./gradlew :wallet:test
        working-directory: Android

      - name: Run Android Instrumented Tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 29
          working-directory: Android
          script: ./gradlew :wallet:connectedAndroidTest 
