name: Android Instrumentation Tests

on: [push, pull_request]

jobs:
  instrumented-tests:
    runs-on: ubuntu-latest
    timeout-minutes: 15  # ensure enough time for emulator startup and tests
    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 11

      # Enable KVM for hardware acceleration (Ubuntu runners)
      - name: Enable KVM group perms
        run: |
          echo 'KERNEL=="kvm", GROUP="kvm", MODE="0666", OPTIONS+="static_node=kvm"' | sudo tee /etc/udev/rules.d/99-kvm4all.rules
          sudo udevadm control --reload-rules
          sudo udevadm trigger --name-match=kvm

      # Launch emulator and run tests
      - name: Run Android instrumented tests
        uses: ReactiveCircus/android-emulator-runner@v2
        with:
          api-level: 30                      # Use Android API 30 (for example)
          target: google_apis               # Use Google APIs system image&#8203;:contentReference[oaicite:21]{index=21}
          arch: x86_64                      # Use x86_64 image
          profile: Nexus 6                  # (Optional) Device profile to use
          emulator-options: >              # Override default launch options
            -no-window -gpu swiftshader_indirect -no-snapshot -noaudio -no-boot-anim 
            -camera-back none -camera-front none
          disable-animations: true         # Disable UI animations on the emulator
          script: ./gradlew connectedCheck  # Run instrumentation tests (Gradle connected tests)
