name: Android Instrumentation Tests

on: [push, pull_request]

jobs:
  connected-tests:
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: 11
          distribution: 'adopt'
          cache: 'gradle'

      - name: Set up Android SDK
        run: |
          echo "ANDROID_HOME=$HOME/Library/Android/sdk" >> $GITHUB_ENV
          echo "ANDROID_SDK_ROOT=$HOME/Library/Android/sdk" >> $GITHUB_ENV
          echo "$ANDROID_HOME/cmdline-tools/latest/bin:$ANDROID_HOME/tools/bin:$ANDROID_HOME/platform-tools" >> $GITHUB_PATH

      - name: Ensure emulator is installed
        run: |
          yes | sdkmanager --install "system-images;android-30;google_apis;x86_64"
          sdkmanager --licenses

      - name: Grant execute permission for Gradle wrapper
        run: chmod +x ./gradlew

      - name: Run connected tests
        uses: ReactiveCircus/android-emulator-runner@v2
        with:
          api-level: 30
          target: google_apis
          arch: x86_64
          script: |
            adb wait-for-device
            adb devices -l
            adb shell "while [[ -z $(getprop sys.boot_completed) ]]; do sleep 1; done"
            ./gradlew :wallet:connectedDebugAndroidTest --stacktrace
