name: Android Build

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Check architecture
        run: uname -m

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'temurin'
          cache: 'gradle'

      - name: Set up Gradle
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: 8.13

      - name: Make gradlew executable
        run: chmod +x gradlew
        
      - name: Navigate to Project Directory
        run: cd Android/wallet
        
      - name: Build Debug
        run: .cd Android/wallet && gradle assembleDebug --stacktrace 
