name: generate-doc

on:
  release:
    types: [published]

jobs:
  generate-doc:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          path: master

      - name: Get tag
        id: vars
        run: echo "tag=${GITHUB_REF#refs/*/}" >> $GITHUB_OUTPUT
        working-directory: master

      - name: Setup Swift
        uses: swift-actions/setup-swift@v1
        with:
          swift-version: "5.5"

      - name: Install jazzy
        run: |
          gem install jazzy

      - name: Build doc
        env:
          RELEASE_VERSION: ${{steps.vars.outputs.tag}}
        run: |
          jazzy \
            --clean \
            --output .build/jazzy \
            --author 'Flow Wallet Mobile Team' \
            --author_url https://github.com/onflow \
            --github_url https://github.com/onflow/flow-wallet-kit \
            --github-file-prefix https://github.com/onflow/flow-wallet-kit/tree/${RELEASE_VERSION} \
            --module FlowWalletKit \
            --module-version ${RELEASE_VERSION} \
            --swift-build-tool spm \
            --build-tool-arguments -Xswiftc,-swift-version,-Xswiftc,5.5
        working-directory: master
      
      - name: Checkout doc
        uses: actions/checkout@v3
        with:
          ref: gh-pages
          path: gh-pages

      - name: Clean old doc
        run: rm -rf docs/current
        working-directory: gh-pages

      - name: Copy new doc
        env:
          G_WORKSPACE: ${{github.workspace}}
          RELEASE_VERSION: ${{steps.vars.outputs.tag}}
        run: |
          mkdir -p docs/current
          mkdir -p docs/$RELEASE_VERSION
          cp -R ${G_WORKSPACE}/master/.build/jazzy/* docs/current
          cp -R ${G_WORKSPACE}/master/.build/jazzy/* docs/$RELEASE_VERSION
        working-directory: gh-pages

      - name: Commit
        env:
          RELEASE_VERSION: ${{steps.vars.outputs.tag}}
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "generate ${RELEASE_VERSION} docs automatically"
          git push
        working-directory: gh-pages
