name: Manual Publish

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Version to publish (e.g., 0.1.0 or 0.1.0-SNAPSHOT)"
        required: true
        default: "0.0.0-test"

permissions:
  contents: read
  packages: write

jobs:
  publish:
    runs-on: macos-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: 'temurin'
          cache: 'gradle'

      - name: Set up Gradle
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: 8.14.1
          build-root-directory: Android/wallet
          arguments: assembleRelease publish -x test --no-configure-on-demand --no-daemon --info
        env:
          # Use non-reserved env var names mapped from secrets that also avoid GITHUB_ prefix
          GPR_USER: ${{ secrets.GPR_USER }}
          GPR_TOKEN: ${{ secrets.GPR_TOKEN }}
          ORG_GRADLE_PROJECT_VERSION_NAME: ${{ inputs.version }}

      - name: Collect Reports and Logs
        if: failure()
        run: |
          mkdir -p reports
          cp -r Android/wallet/build/reports/tests reports/tests || echo "No test reports found"
          cp -r Android/wallet/build/reports reports/gradle-reports || echo "No Gradle reports found"

      - name: Upload All Reports
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: all-reports
          path: reports
