on:
  release:
    types: [created]

permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: macos-latest
    steps:
      # Step 1: Checkout the code
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Setup Java environment
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'temurin'
          cache: 'gradle' # Enables caching for Gradle dependencies

      # Step 3: Set up Gradle and publish
      - name: Set up Gradle
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: 8.13
          build-root-directory: Android/wallet
          arguments: check publish --no-configure-on-demand --no-daemon --info
        env:
          ORG_GRADLE_PROJECT_githubUsername: ${{ secrets.WALLET_CORE_USER }}
          ORG_GRADLE_PROJECT_githubPassword: ${{ secrets.WALLET_CORE_TOKEN }}
          ORG_GRADLE_PROJECT_VERSION_NAME: ${{ github.event.release.tag_name }}

      # Step 4: Collect all reports and logs
      - name: Collect Reports and Logs
        if: failure() # Only run if the previous step fails
        run: |
          mkdir -p reports
          # Copy test reports
          cp -r Android/wallet/build/reports/tests reports/tests || echo "No test reports found"
          # Copy Gradle build logs
          cp -r Android/wallet/build/reports reports/gradle-reports || echo "No Gradle reports found"

      # Step 5: Upload all reports and logs
      - name: Upload All Reports
        if: failure() # Only run if the previous step fails
        uses: actions/upload-artifact@v4
        with:
          name: all-reports
          path: reports
