on:
  release:
    types: [created]

jobs:
  build:
    runs-on: macos-latest
    steps:
      # Step 1: Checkout the code
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Setup Java environment
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'temurin'
          cache: 'gradle' # Enables caching for Gradle dependencies

      # Step 3: Run Gradle build and test
      - name: Build and Test
        run: |
          cd Android && ./gradlew :wallet:check :wallet:assemble :wallet:publishToMavenLocal --no-configure-on-demand --no-daemon --info

      # Step 4: Collect all reports and logs
      - name: Collect Reports and Logs
        if: failure() # Only run if the previous step fails
        run: |
          mkdir -p reports
          # Copy test reports
          cp -r wallet/build/reports/tests reports/tests || echo "No test reports found"
          # Copy Gradle build logs
          cp -r wallet/build/reports reports/gradle-reports || echo "No Gradle reports found"

      # Step 5: Upload all reports and logs
      - name: Upload All Reports
        if: failure() # Only run if the previous step fails
        uses: actions/upload-artifact@v4
        with:
          name: all-reports
          path: reports